jCONFIG_ZMK_KEYBOARD_NAME="ZEN"
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_CDC_ACM_BOOTLOADER_TRIGGER=y
CONFIG_ZMK_STATUS_LED=y
CONFIG_ZMK_IDLE_TIMEOUT=300000
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=9000000
CONFIG_ZMK_NON_LIPO_MIN_MV=1000
CONFIG_ZMK_NON_LIPO_LOW_MV=900
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y
CONFIG_INPUT_THREAD_STACK_SIZE=4096
CONFIG_BT_MAX_CONN=5
CONFIG_BT_MAX_PAIRED=5
CONFIG_ZMK_STUDIO_TRANSPORT_BLE=y
